apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: NodePort  # Use NodePort if you're running on Minikube
  selector:
    app: mysql
  ports:
    - port: 3306       # MySQL default port
      targetPort: 3306
      nodePort: 30081
