apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: NodePort  # Use NodePort if you're running on Minikube
  selector:
    app: mysql
  ports:
    - port: 3306        # host port
      targetPort: 3306  # Container port
      nodePort: 30081   # kubernetes nodeport external access
